name: Export Schematics on Push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  export-schematics:
    uses: ./.github/workflows/export-schematic-pdfs.yml
    with:
      artifact-name: schematics-pdfs-${{ github.sha }}

  export-prod-files:
    uses: ./.github/workflows/export-pcb-prod.yml
    with:
      artifact-name: prod-files-${{ github.sha }}
